[supervisord]
nodaemon=true
logfile=/dev/stdout
logfile_maxbytes=0
loglevel=warn
user=root

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=10

[program:gunicorn]
command=/home/frappe/frappe-bench/env/bin/gunicorn
    --chdir=/home/frappe/frappe-bench/sites
    --bind=0.0.0.0:8000
    --threads=4
    --workers=2
    --worker-class=gthread
    --worker-tmp-dir=/dev/shm
    --timeout=120
    --preload
    frappe.app:application
user=frappe
directory=/home/frappe/frappe-bench
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=20

[program:socketio]
command=node /home/frappe/frappe-bench/apps/frappe/socketio.js
user=frappe
directory=/home/frappe/frappe-bench
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
environment=HOME="/home/frappe",PATH="/home/frappe/.nvm/versions/node/v%(ENV_NODE_VERSION)s/bin:%(ENV_PATH)s"
priority=30

[program:worker-short]
command=/home/frappe/frappe-bench/env/bin/python -m frappe.utils.bench_helper frappe worker --queue short,default
user=frappe
directory=/home/frappe/frappe-bench
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=40

[program:worker-long]
command=/home/frappe/frappe-bench/env/bin/python -m frappe.utils.bench_helper frappe worker --queue long,default,short
user=frappe
directory=/home/frappe/frappe-bench
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=50

[program:scheduler]
command=/home/frappe/frappe-bench/env/bin/python -m frappe.utils.bench_helper frappe schedule
user=frappe
directory=/home/frappe/frappe-bench
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=60
